baseURL = 'https://matkv.dev/'
title = 'matkv.dev'

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[params]
description = "This is my digital garden and a place for me to share my thoughts & interests."
github = "https://github.com/matkv"
email = "mailto:mail@matkv.dev"
copyright = "matkv 2025"

[[menu.main]]
	name = "now"
	url = "/now"
	weight = 1

[[menu.main]]
	name = "log"
	url = "/log/"
	weight = 2

[[menu.main]]
	name = "library"
	url = "/library/"
	weight = 3

[[menu.main]]
	name = "garden"
	url = "/garden/"
	weight = 4

[[menu.main]]
	name = "projects"
	url = "/projects"
	weight = 5