baseURL = 'https://matkv.dev/'
title = 'matkv.dev'

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[params]
description = "This is the description."

# Main menu definition
[[menu.main]]
	name = "library"
	url = "/library/"
	weight = 1

[[menu.main]]
	name = "garden"
	url = "/garden/"
	weight = 2

[[menu.main]]
	name = "log"
	url = "/log/"
	weight = 3

[[menu.main]]
	name = "projects"
	url = "/projects"
	weight = 4